# Health, Wellbeing, and Equity {.unnumbered}

## Sexual Misconduct {.unnumbered}

- UCLA's [Sexual Violence Index](https://www.sexualharassment.ucla.edu/Portals/42/Documents/UCLA%20Sexual%20Violence%20Index%20062018.pdf), including definitions, more thorough descriptions of available resources, and suggested safety measures. 
- [Title IX Office](sexualharassment.ucla.edu).
- [Office of the Dean of Students](deanofstudents.ucla.edu).
- [UCLA Police Department (UCPD)](ucpd.ucla.edu)

### Confidential Resources {.unnumbered}

[Campus Assault Resources & Education (CARE)](https://careprogram.ucla.edu/)
  - Crisis support available 24 hours a day: (310) 206-2465

[Counseling and Psychological Services (CAPS)](https://www.counseling.ucla.edu/)
  - Counselors available by phone 24 hours a day: (310) 825-0768

[Rape Treatment Center UCLA Medical Center Santa Monica](https://www.uclahealth.org/santa-monica/rape-treatment)
  - Support available 24 hours a day: (424) 259-7208

[Student Legal Services](https://www.studentlegal.ucla.edu/)
  - Available Monday-Friday, 9am-12pm and 1pm-5pm
  - $10 initial consultation fee, **currently waived due to COVID-19.**

### My Obligations under Title IX {.unnumbered}

I am a Responsible Employee, which means that I am required by the University to report incidents of sexual harassment or sexual violence to the Title IX Coordinator. **If you disclose such an incident to me, I will report it to the Title IX Coordinator.** This may lead to follow-up from the Title IX office and a possible investigation into the incident. If you would like to speak to a resource who will maintain strict confidentiality, see [Confidential Resources](#confidential-resources).


## Mental Health {.unnumbered}

[Counseling and Psychological Services (CAPS)](https://www.counseling.ucla.edu/)
  - Counselors available by phone 24 hours a day: (310) 825-0768

## Students with Disabilities {.unnumbered}

[Office for Students with Disabilities (OSD)](http://www.osd.ucla.edu)
  - Provides academic support services for students with documented permanent or temporary disabilities, at no cost to students. Example services include readers, adaptive equipment, sign language interpreters, test-taking arrangements, transportation, and much more. 

[UCLA Disabilities and Computing Program (DCP)](http://www.dcp.ucla.edu)
  - Provides services related to accessible computing technology, including support for students and training for faculty. 

## Equity, Inclusion, and Access {.unnumbered}

The [Office of Equity, Diversity, and Inclusion](https://equity.ucla.edu/about-us/) maintains a [list of resources](https://equity.ucla.edu/programs-resources/). Several highlights:
  - [Resources for Racial Trauma](https://equity.ucla.edu/know/resources-for-racial-trauma/)
  - [Resources on Immigration Policy Changes](https://equity.ucla.edu/know/immigration/)
  - [Resources on Native American and Indigenous Affairs](https://equity.ucla.edu/know/resources-on-native-american-and-indigenous-affairs/)

The [Community Programs Office](http://www.cpo.ucla.edu/cpo/) offers several student-run programs aimed at the development of an inclusive and diverse community of scholars and leaders on and off campus. 
  - The [Student Retention Center](http://www.cpo.ucla.edu/src/) offers several programs supporting students who may be experiencing difficulties in their academic or social lives. Specific populations served include students within the Afrikan diaspora, Raza students, Native and Indigenous students, Pilipino students, and Southeast Asian students. 
  - [Academic Advancement Program (AAP) Peer Learning](https://www.aap.ucla.edu/units/peer-learning) (serving AAP students).

## International Students {.unnumbered}

[Dashew Center for International Students and Scholars](https://www.internationalcenter.ucla.edu/resources/menu) 
  - [List of resources](https://www.internationalcenter.ucla.edu/resources/resource-guide) related to visas, arrival in the US, housing, and other important topics. 

## Financial Stress {.unnumbered}

- [Bruin Shelter](http://www.bruinshelter.org/) provides a safe, supportive environment for fellow college students experiencing homelessness by fostering a collaborative effort between universities, community-based organizations, and service providers.
- The [CPO Food Shelter](http://www.cpo.ucla.edu/cpo/foodcloset/) provides free food for any UCLA student who may be experiencing hunger and/or struggling to attain food due to financial hardships.

# (PART\*) Lecture Notes {.unnumbered}